# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anyi Rao
email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
  
url: "https://softwarelight.github.io/" # the base hostname & protocol for your site

baseurl: 
permalink: /:title/

analytics: 
disqus-shortname:

#color scheme
color-1: '#E64C3C'
color-2: '#F0C419' 

# Author pictre 100x100 --> keep it inside img folder.
author-image: 
author-name: 'Anyi Rao'
author-about: 'Enjoy life!' 

# Build settings
markdown: kramdown

sass:
    style: compressed




#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
  
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    
gems: [jekyll-seo-tag]
